name: personal-check

on:
  push:
    branches: [ "main", "draft" ]
  pull_request:
    branches: [ "main" ]

jobs:

  test_and_lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install poetry 
        run: pipx install poetry
      - name: Install python
        uses: actions/setup-python@v4
        with: 
          python-version: '3.10'
          cache: 'poetry'
      - name: Install dependencies
        run: make install
      - name: Lints
        run: make lint
      - name: make tests
        run: make test
